services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookmarks
      MYSQL_USER: ${DB_CRED}
      MYSQL_PASSWORD: ${DB_CRED}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    networks:
      - my-net
    ports:
      - "3308:3306"

  backend:
    build: ./bookmark
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - my-net
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_CRED}
      SPRING_DATASOURCE_PASSWORD: ${DB_CRED}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_AUDIENCES: ${OAUTH_AUD}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${OAUTH_ISSUER}

  frontend:
    build: ./bookmark_fe
    networks:
      - my-net
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started

networks:
  my-net:
volumes:
  mysql-data:
